# Site settings
title: A blog about lorem ipsum dolor sit amet
description: A blog about lorem ipsum dolor sit amet
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://heypaprika.github.io/blog/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Chang-Hyun Lee
user_title: AI Developers
user_description: Bicycle rights irony actually neutra typewriter lyft. Man bun taxidermy put a bird on it, umami yr ramps pop-up ugh bushwick chia lo-fi. Occupy bitters pour-over snackwave you probably haven't heard of them small batch. Cornhole mustache man bun letterpress echo park VHS.
email: kw.artint@gmail.com
twitter_username: ""
github_username:  Artinto
gplus_username:  kw.artint

# Google-analytics
google-analytics:
  id: ""

links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

exclude: ['package.json', 'src' , 'node_modules']
